oauthClient:
  redirectUris:
      - http://localhost/login/callback
    # - http://localhost:4200/login/callback
  applicationType: browser
trustedOrigins: 
  - http://localhost

directions: |+2
  Okta configuration written to: .okta.env
  
  Build this example using NPM:

      npm install

  And run with:

      npm start
